### ISSUE TITLE
Appointments with same start and end time spanning two days

### ISSUE THREAD

**Issue by Whitling2k** [MMRIZE/MMM-CalendarExt3#118]
As above, appointments with same start and end time (i.e. 0 minute duration reminders) span across two days when rendered in the calendar.  It appears that Calendar EXT3 (or the main calendar module?) are mis-rendering the events.

![Screenshot 2023-11-23 114318](https://github.com/MMRIZE/MMM-CalendarExt3/assets/119603945/b19f2177-bd14-4069-9ff5-f1521a32e04a)

![Outlook calendar](https://github.com/MMRIZE/MMM-CalendarExt3/assets/119603945/79ebbe2a-0f8c-487b-aab8-8b2de95bd3d5)

![Screenshot 2023-11-23 114423](https://github.com/MMRIZE/MMM-CalendarExt3/assets/119603945/a2815fab-12ef-4f87-bc1c-6604ff831545)

**Comment by eouia** [comment]
Thanks. I’ll look inside.

**Comment by eouia** [comment]
Hmmmm... weird. In my test, there is no problem at all.
![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/1720610/a42577a4-85bd-4155-a07f-61162c8780a9)

<img width="188" alt="image" src="https://github.com/MMRIZE/MMM-CalendarExt3/assets/1720610/e3fecd5f-ee54-4744-aa4c-e94cdeed1726">


I have no outlook calendar so I couldn't test it. But I cannot guess without the real ics.
Could you share me the ics URL or downloaded ics file? (eouia0819@gmail.com)
