### ISSUE TITLE
Error with Commit 20th Dec 2023. Had to revert to previous commit

### ISSUE THREAD

**Issue by MickCrozier** [MMRIZE/MMM-CalendarExt3#121]
TypeError: Cannot read properties of undefined (reading 'identifier')
    at regularizeEvents (CX3_shared.mjs:30:24)
    at Class.draw (MMM-CalendarExt3.js:659:21)
    at Class.getDom (MMM-CalendarExt3.js:375:16)
    at main.js:138:35
    at new Promise (<anonymous>)
    at updateDom (main.js:118:10)
    at Object.updateDom (main.js:676:4)
    at Class.updateDom (module.js:335:6)
    at Class.updateAnimate (MMM-CalendarExt3.js:681:10)
    at MMM-CalendarExt3.js:166:14

**Comment by eouia** [comment]
Could you check your CX3_Shared.mjs? I think your update is not completed fully. What is the first 10 lines of your file?
It should be this;
https://github.com/MMRIZE/CX3_Shared/blob/44c7176e2b79a12e76badb78a49455bd7fbb22e3/CX3_shared.mjs#L1-L20

Try this;
```sh
cd ~/MagicMirror/modules/MMM-CalendarExt3
git submodule update --init --recursive
```

**Comment by soaringsax** [comment]
Same issue here, running the submodule update did not fix it. Blowing away the entire repo and reinstalling did not fix it either. For what it's worth, MMM-CalendarExt3Agenda also has failed to load.

**Comment by eouia** [comment]
@soaringsax @MickCrozier
Can you post first 20 lines of these files of your installation?
1. `MMM-CalendarExt3/CX3_Shared/CX3_shared.mjs`
2. `MMM-CalendarExt3Agenda/CX3_Shared/CX3_shared.mjs`
Both 2 files are slightly different. Maybe some conflicts might happen.

**Comment by ChickenBeard** [comment]
1. MMM-CalendarExt3/CX3_Shared/CX3_shared.mjs
`/**
 * @module CX3_shared
 */


const MAGIC_IDENTIFIER = 'CX3_MAGIC'
const ICONIFY_URL = 'https://code.iconify.design/iconify-icon/1.0.8/iconify-icon.min.js'

const loaded = true
const uid = Date.now()

const magicPool = new Map()

/**
 * Get contrast color for better visibility from the given rgba color
 * @param {string} rgba
 * @returns string black or white
 */
const getContrastYIQ = (rgba) => {
  let [r, g, b, a] = rgba.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+\.{0,1}\d*))?\)$/).slice(1)`

**Comment by ChickenBeard** [comment]
> Could you check your CX3_Shared.mjs? I think your update is not completed fully. What is the first 10 lines of your file? It should be this; https://github.com/MMRIZE/CX3_Shared/blob/44c7176e2b79a12e76badb78a49455bd7fbb22e3/CX3_shared.mjs#L1-L20
> 
> Try this;
> 
> ```shell
> cd ~/MagicMirror/modules/MMM-CalendarExt3
> git submodule update --init --recursive
> ```

Manually downloading and using the CX3_Shared.mjs linked seemed to resolve the issue for me.

**Comment by soaringsax** [comment]
@eouia From "MMM-CalendarExt3/CX3_Shared/CX3_shared.mjs"
```
/**
 * @module CX3_shared
 */


const MAGIC_IDENTIFIER = 'CX3_MAGIC'
const ICONIFY_URL = 'https://code.iconify.design/iconify-icon/1.0.8/iconify-icon.min.js'

const loaded = true
const uid = Date.now()

const magicPool = new Map()

/**
 * Get contrast color for better visibility from the given rgba color
 * @param {string} rgba
 * @returns string black or white
 */
const getContrastYIQ = (rgba) => {
  let [r, g, b, a] = rgba.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+\.{0,1}\d*))?\)$/).slice(1)

```
From "MMM-CalendarExt3Agenda/CX3_Shared/CX3_shared.mjs"

/```
/ This file is reserved to refactor all CX3* modules, so atm it is doing nothing but needed. Don't touch this.
const MAGIC_IDENTIFIER = 'CX3_MAGIC'

const loaded = true
const uid = Date.now()

const magicPool = new Map()

const getL = (rgba) => {
  let [r, g, b, a] = rgba.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+\.{0,1}\d*))?\)$/).slice(1)
  r /= 255
  g /= 255
  b /= 255
  const l = Math.max(r, g, b)
  const s = l - Math.min(r, g, b)
  const h = s ? l === r ? (g - b) / s : l === g ? 2 + (b - r) / s : 4 + (r - g) / s : 0
  // let rh = 60 * h < 0 ? 60 * h + 360 : 60 * h
  // let rs = 100 * (s ? (l <= 0.5 ? s / (2 * l - s) : s / (2 - (2 * l - s))) : 0)
  let rl = (100 * (2 * l - s)) / 2
  return rl
```
