### ISSUE TITLE
Calender Not Loading

### ISSUE THREAD

**Issue by jrbrewster** [MMRIZE/MMM-CalendarExt3#126]
Only stopped working since latest update.

Running docker image: karsten13/magicmirror:latest (Magic Mirror v2.25.0
npm v10.2.3
node v20.10.0

See screenshot.

![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/153390780/01ba6b4e-1cee-47f1-b482-79d984ffdfe7)

**Comment by eouia** [comment]
Check your electron/chromium version. It requires > Chromium 110.
You can check `navigator.userAgent` in dev-console.
