### ISSUE TITLE
Suggestion: Week mode starting on Today. 

### ISSUE THREAD

**Issue by BKeyport** [MMRIZE/MMM-CalendarExt3#138]
Please add ability to start the week mode week starting "Today" -- 

I figure this could be triggered easiest by setting firstDayOfWeek to -1 and testing for it.

**Comment by eouia** [comment]
??? mode: `day` is for that?

**Comment by BKeyport** [comment]
Okay, I see that now.... "Day" to me is a single day. 

Thanks!
