### ISSUE TITLE
Reoccurring single full day events span two days

### ISSUE THREAD

**Issue by Muffexx** [MMRIZE/MMM-CalendarExt3#139]
Hello there :)

I'm using the most current versions of MM and Ext3 as of today.

The module does show some of the single full day events for two days.

![FullDayIssue](https://github.com/MMRIZE/MMM-CalendarExt3/assets/33467400/f8eec720-e04b-4ed5-b197-d5486d82b5c3)

All events in the orange calendars are single full day events. Some of them are shown correctly and some span two days. Maybe this issue is related to summer time in Germany?

MM config:
`
        language: "en",
        timeFormat: 24,
        timeZone: "Europe/Berlin",
`

Calendar module config:
`
                module: "calendar",
                config: {
                        broadcastPastEvents: true,
                        maximumEntries: 80,
                        calendars: [{...
`

Ext3 module config:
`
                        animationSpeed: 0,
                        calendarSet: ['General','Birthdays','Important','Uni','Trash'],
                        firstDayOfWeek: 1,
                        fontSize: '22px',
                        locale: 'en-DE',
                        maxEventLines: 6,
                        mode: "week",
                        useSymbol: true,
                        weekIndex: 0,
                        weeksInView: 2
`

Any ideas?

regards

**Comment by Welle05** [comment]
Same Problem with me! Since summer time change single full day events span to two days. I can add a hint: only full day events which are part of a series (i.e. birthdays, or weekly reminders). Everything is fine in the original (google Kalender) as well as in Standard Calendar Module,.....

**Comment by eouia** [comment]
Could you post the ics file here or send to me?(eouia0819@gmail.com)

**Comment by matt-thurling** [comment]
I've been getting this too with all-day reoccurring events ever since the latest MagicMirror update. It looks like one-off all day events have their time displayed as 12am til 11.59pm on the same day, but the re-occurring ones are 10am from one day til 10am the next. My timezone is +10GMT which makes me think that's relevant. It's possibly not an issue with your module but the default calendar sending through the wrong times in its notifications for re-occurring all day events?

**Comment by Welle05** [comment]
BEGIN:VEVENT
DTSTART;VALUE=DATE:20240424
DTEND;VALUE=DATE:20240425
RRULE:FREQ=MONTHLY;WKST=MO;INTERVAL=3;BYDAY=-1WE
DTSTAMP:20240407T102050Z
UID:cgr38cb570r3ebb26sq32b9k6gs38b9o64qjgbb171ij2cr3c8q3aopg70@google.com
CREATED:20240303T133353Z
LAST-MODIFIED:20240303T133458Z
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Bluttest Hautarzt 
TRANSP:TRANSPARENT
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P0DT7H0M0S
DESCRIPTION:This is an event reminder
END:VALARM
END:VEVENT


I am not an expert in calendars but it seems that the "two days" are already in the google ics File. But in Google it is shown correctly and also in CAlendar Standard Module....

**Comment by eouia** [comment]
Updated to fix it. Check it.

**Comment by Muffexx** [comment]
Works. Thank you. :)

**Comment by Muffexx** [comment]
I rejoiced too soon. Had not waited until all calendars were loaded.
Now some full day events span three days.

![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/33467400/33d7f347-2d99-4cf7-9d89-83e3064a16b7)

**Comment by Welle05** [comment]
Same with me not working after update....
@eoia0819: See ics file above

**Comment by eouia** [comment]
> Same with me not working after update.... @eoia0819: See ics file above

what does it mean "not working after update"? I need a more accurate description or screenshot (even with a photo from handy)

**Comment by eouia** [comment]
@Muffexx @Welle05 
I need more details to what happened.

Read this (https://github.com/MMRIZE/MMM-CalendarExt3/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) and make a new issue for each case.

**Comment by eouia** [comment]
Finally I found what was wrong. 

The issue lies in the wrong parsing logic from the default calendar module about repeated full-day events with TimeZone by RRULE. 

If you have installed CX3 v1.8.2, Reinstall again or back to 1.8.1 (I rolled back again to 1.8.1)

Then see this;
https://github.com/MMRIZE/MMM-CalendarExt3/wiki/To-fix-wrong-repeated-fullday-event-displaying-%28MM-2.27%29
