### ISSUE TITLE
ERROR! Could not find main module js file for MMM-CalendarEXT3

### ISSUE THREAD

**Issue by egarrison89** [MMRIZE/MMM-CalendarExt3#145]
I've been trying to get this module to work however I seem to be running into an issue. I've removed and reinstalled the module with no change. In my config.js file I am using the most basic config (see below)
{
  module: "MMM-CalendarExt3",
  position: "bottom_bar",
},

There is nothing displayed on the MM when I run the program. Not even an outline of the calendar. I've previously used the MMM-MonthlyCalendar module and have had no issues however CalendarEXT3 has additional customization options I'm after.

Has anyone else had an issue where the js file is said to be missing however when I look in the directory everything is there as it should be. While I'm comfortable with coding within reason I'd best be described as a hobbiest. All other modules work without issue.

[2024-04-20 18:12:22.954] [WARN]  No /home/egarrison/MagicMirror/js/../modules/MMM-CalendarExt3/MMM-CalendarExt3.js found for module: MMM-CalendarExt3. 
[2024-04-20 18:12:24.660] [ERROR] ERROR! Could not find main module js file for MMM-CalendarEXT3 
![IMG_5212](https://github.com/MMRIZE/MMM-CalendarExt3/assets/167653521/70663e96-0daa-402e-b06a-2f763085731f)

**Comment by eouia** [comment]
> [2024-04-20 18:12:22.954] [WARN] No /home/egarrison/MagicMirror/js/../modules/MMM-CalendarExt3/MMM-CalendarExt3.js found for module: MMM-CalendarExt3.
[2024-04-20 18:12:24.660] [ERROR] ERROR! Could not find main module js file for MMM-CalendarEXT3

This shows, the module is not installed. 
Check the path of the module. Your module path looks very weird. Usually each module should be installed and placed in this path

```sh
<Your MagicMirror Directory>/modules/<Each Module>
```
In your case, It should be;
```sh
/home/egarrison/MagicMirror/modules/MMM-CalendarExt3
```

But your error message is pointing out another directory. It is not usual.
I suspect you may have modified some core files or something happens. 

What I suggest is;
1) Rename your current MM directory to another for backup.
2) Install new MM
3) Only install MMM-CalendarExt3 alone.
4) Try to test. Let's see what happen.

**Comment by egarrison89** [comment]
@eouia I just started from a fresh MM installation and installed only this module to test. Receiving the same error code. I have not edited any core files and have only added the CalendarEXT3 module to the config.js file.

**Comment by eouia** [comment]
Weird. 
The error message says MMM-CalendarExt3 is not placed in proper location.

```sh
cd /
ls /home/egarrison/MagicMirror/modules/MMM-CalendarExt3/MMM-CalendarExt3.js
```
What is the result? It should show;
```
/home/egarrison/MagicMirror/modules/MMM-CalendarExt3/MMM-CalendarExt3.js
```
right?

**Comment by eouia** [comment]
I'll close this because no more conversation continued.
