### ISSUE TITLE
Birthdays (repeatable events) are wrong

### ISSUE THREAD

**Issue by Antislag** [MMRIZE/MMM-CalendarExt3#15]
Hello,

first of all thanks for the gread module!
I have an issue with repeatable events (e.g. birthdays)

For example there is a repeatable event in my GoogleCalendar on 07.June but on the MagicMirror the Event is shown on 07.08.

Do you know how I can fix this?

Thanks in advace.

**Comment by eouia** [comment]
First, check this.
- Is that event also displayed as wrong on the default MagicMirror `calendar` module?
- Where the calendar comes from? Is your own managed calendar on Google calendar by manual? or from another `ICAL(.ics)` URL? Some external ICAL feeds might have the wrong timezone formats. Google Calendar smartly handle the wrong data, but MM's default might not. 

Could you send me the URL(ICAL `.ics`) of the calendar to look inside? (eouia0819@gmail.com)

**Comment by eouia** [comment]
there was no reply. so I'll close this issue.
