### ISSUE TITLE
not showing on MM

### ISSUE THREAD

**Issue by Brew-tus** [MMRIZE/MMM-CalendarExt3#16]
here are my configs and when I run MM nothing appears on my screen. Am I missing something?
		{
			module: "MMM-CalendarExt3",
			position: "lower_third",
			title: "",
			config: {
				mode: "month",
				locale: 'de-DE',
				maxEventLines: 5,
				firstDayOfWeek: 1,
				calendarSet: ["us_holiday"],

{
			module: "calendar",
			header: "Events",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar",
						url: LEFT BLANK ON PURPOSE
						name: "us_holiday",
				maximumEntries: 19,
				maximumNumberOfDays: 365,
				broadcastEvents: true,
				displaySymbol: true,
				showLocation: true,
				fetchInterval: 300000,
				animationSpeed: 2000,
				colored: false,
				coloredSymbolOnly: false		
					}

**Comment by eouia** [comment]
Does 'nothing appears' mean the entire black screen on your mirror? or  just CX3 module is not showing (but other modules are displayed as usual)?
Can you show me the screen capture (or taking a photo with your phone)?

**Comment by Brew-tus** [comment]
Other modules display as usual just the CX3 doesn't display at all.

![IMG_4097](https://user-images.githubusercontent.com/111465259/185587305-f13d0a0a-a25d-446a-ba3c-4b1f976afa27.PNG)

**Comment by eouia** [comment]
![image](https://user-images.githubusercontent.com/1720610/185591690-908f2e71-2564-4a8e-b8c4-86e501449b2f.png)
Hmmm... seems nothing wrong in your config.

<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>i</kbd> (Or alternates by OS) would open the dev console on your mirror. Or you can start mirror by
```sh
npm run start:dev
```
(you need to stop `pm2` before this command)

In your dev console, move to `console` tab then you can see some many logs. Is there any suspicious message?

**Comment by Brew-tus** [comment]
showing me this
<img width="1043" alt="mmm-ext3" src="https://user-images.githubusercontent.com/111465259/185729344-30c5959a-21e0-40d3-b68f-97d3a9dc69b9.png">

**Comment by Brew-tus** [comment]
I rebooted my Raspberry Pi and now it s working
