### ISSUE TITLE
오늘 이전의 일정이 갑자기 모두 안보입니다.

### ISSUE THREAD

**Issue by PaekHyun** [MMRIZE/MMM-CalendarExt3#160]
별다른 것을 하지 않은 것 같은데

갑자기 오늘 이전의 모든 일정이 안보이고, 오늘부터의 일정만 보입니다.

혹시나 해서 config파일에서

skipPassedEventToday : false, 혹은 true로 바꾸어도 똑같이 오늘 이전의 일정이 모두 표기가 안됩니다.

혹시 이런 경우가 있을까요?

**Comment by eouia** [comment]
실제 config파일이나, 현재 읽어들이고 있는 ics 파일들의 실물 내용을 가지고 파악해야 좀 더 정확하게 답변드릴 수 있겠습니다만;
일단 생각나는, 가능한 원인으로써;

1. `calendar` module 설정 문제;
CX3는 calendar에서 notification으로 보내는 이벤트들만 가지고 화면에 표시하기 때문에, calendar 모듈 자체가 이벤트를 못읽어들이거나, notification으로 내보내지 못하는 경우 문제가 될 수 있습니다.
관련있는 config properties는,
- broadcastEvents
- excluededEvents
- broadcastPastEvents (디폴트로 false로 되어 있기 때문에 이 문제일 가능성이 큽니다.)
- maximunNumberOfDays
- maximumEntries

2. 그 외에는,  실제 데이터를 봐야만 알 수 있을 것 같아요. 혹시 특별히 문제가 안된다면 config파일을 보내주시겠어요? (실제 사용하고 있는 ics url, file들 포함하여.)  => eouia0819@gmail.com

**Comment by PaekHyun** [comment]
감사합니다. ㅠㅠ
broadcastPastEvents 이 옵션이었군요...
( 이 옵션이 calendar_ext3옵션인줄알고 한참을 헤맸는데...기본 calendar 옵션이네요 ;;)
월초에 테스트 해보다가 바빠서 이제 다시 했더니 이런 일이 생겼네요.. ;;

답변 감사합니다.  :)
