### ISSUE TITLE
broadcastPastEvents issues

### ISSUE THREAD

**Issue by Brew-tus** [MMRIZE/MMM-CalendarExt3#17]
Now that I finally have the calendar up and running just fine. I went in to add broadcastPastEvents: true, and when I run magic mirror none of my calendars load in either place. However, when I remove that they all load back up but only from todays date on. Here is my setup. Any help would be greatly appreciated 

module: "MMM-CalendarExt3",
position: "upper_third",
title: "",
config: {
mode: "month",
maxEventLines: 5,
firstDayOfWeek: 0,
calendarSet: ["us_holiday", "family", "Reffing", "holidays"],
} 
}, 
{
module: "calendar",
header: "Events",
position: "top_left",
config: {
maxumEnteries:100,
showLocation: true,
calendars:[
{
url: "https://p34-calendars.icloud.com/holidays/us_en-us.ics",
name: "holidays",
color: "yellow"
},
{
url: "xxx......",
name: "family",
color: "red"
},
{
url: "xxx.........",
name: "us_holiday",
color: "orange"
},
{
url: "xxx'',
name: "Reffing",
color: "blue"

**Comment by eouia** [comment]
That is original `calendar` module's issue. The `maximumEntries`(btw, you made a mistype) are gathering 100 entries from all your calendar URL. Old events (from the beginning of each calendar history) might be consuming the entire 100 quota already.

Hmmm. I'll make a standalone ical parser to prevent this. Anyway, MM 2.21 might be fixed for this issue. But not sure at this moment.
