### ISSUE TITLE
Calendar not populating repeating event properly

### ISSUE THREAD

**Issue by pengytek** [MMRIZE/MMM-CalendarExt3#174]
In my Google Calendar I have a weekly repeating event at 7:20PM beginning  Monday, November 18. In MMM_CalendarExt3 it does not show on on November 18 or the next Monday but rather on Sunday, November 24. If I just change the start time to 7PM the problem persists. If I just remove the two other repeating events the problem persists. If I just change it to non-repeating it will properly show up on November 18. If I just change the start time to 9PM it still won't show up on November 18 but will show up on Monday, November 25. I have even tried deleting the calendar and creating a new one.

Here is my Google Calendar:
![image](https://github.com/user-attachments/assets/50f0560c-3175-4edd-b5dc-fed3681777d3)

Here is MagicMirror with no changes:
![image](https://github.com/user-attachments/assets/4bc11527-9a78-42a8-8491-084e199100b4)

Here is MagicMirror with just changing start time to 9PM:
![image](https://github.com/user-attachments/assets/af5bcaca-aaae-433a-bb6a-08636cf6d964)

Here is my config (I know the calendar is private but I'll just delete once the issue is resolved):
```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
  address: "0.0.0.0", // Address to listen on, can be:
  // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
  // - another specific IPv4/6 to listen on a specific interface
  // - "0.0.0.0" to listen on any interface
  // Default, when address config is left out, is "localhost"
  port: 8080,
  ipWhitelist: [], // Set [] to allow all IP addresses
  // or add a specific IPv4 of 192.168.1.5 :
  // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
  // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
  // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

  language: "en",
  timeFormat: 12,
  units: "imperial",

  modules: [
    {
      module: "alert",
    },
    {
      module: "updatenotification",
      position: "top_bar"
    },
    {
      module: "calendar",
      config: {
        colored: true,
	maximumEntries: 50,
        broadcastPastEvents: true,
        calendars: [
	  {
	    name: "taekwondo",
            color: "#8e44ad",
	    url: "https://calendar.google.com/calendar/ical/326ea8a45710a59463908311c287bb532b823ace360866292408f32e8d4335d5%40group.calendar.google.com/private-b16e3bed16e68664dd4b7aec7e8e6e55/basic.ics"
	  }
        ]
      }
    },
    {
      module: "MMM-CalendarExt3",
      position: "top_bar",
      config: {
        mode: "month",
        locale: 'en-US',
        maxEventLines: 5,
        calendarSet: ['taekwondo']
      }
    }
  ]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }
```

**Comment by eouia** [comment]
Have you solved it? Tell me what was the reason and how you fix it.
