### ISSUE TITLE
Can't see events from calendar

### ISSUE THREAD

**Issue by elwood1982uk** [MMRIZE/MMM-CalendarExt3#180]
Using google calendar. The default calendar pulls in events and displays but the bigger *week or month view( calendar you provide doesn't display them - am I missing something pls? have read and tried lots!

**Comment by eouia** [comment]
Possible reasons;
- Maybe your configuration might be wrong (misspelled or something wrong)
- You may need just to wait to represent all the data. Sometimes it will takes some minutes. (Slow internet, slow machine, big calendars, ...)
- Other module may have interferences. (Error or something)

I need your configuration to guess what happens.

And read this doc; it may help;
https://github.com/MMRIZE/MMM-CalendarExt3/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
