### ISSUE TITLE
Center issue

### ISSUE THREAD

**Issue by protorion** [MMRIZE/MMM-CalendarExt3#2]
When I'm trying to place the calendar in middle_center the calendar pushed to the right a bit.

**Comment by eouia** [comment]
Usually, MM's centre position is determined by the left and right parts. If your left position area is wider than the right, your centre position is placed a bit right from the centre line. Current MM's left and right width is not fixed but has dynamic value by contents unless you fix it by force. Check your module's real width on the left and right sides.
