### ISSUE TITLE
webOS 6 incompatibility?

### ISSUE THREAD

**Issue by elorand** [MMRIZE/MMM-CalendarExt3#29]
Hey, 

first off, this is my very first interaction on github, so if I this isn't the right place to write this, I am very sorry.

I am using MagicMirror on my RaspberryPi4b in serveronly mode. When I use my the browser of my LGTV with webOS 6.3.1-414 to show the MagicMirror page, some modules are not shown (default weather, default weather-forecast and MMM-CalendarExt3) and it seems the browser wont stop loading the page (the reload-icon looks like an abort-icon). 
I have tested my configuration on Safari 15.6.1 running on macOS 12.5.1 and other devices, like iPad and even a amazon FireTV stick, which show no problems.

I am not sure about the source of this problem, since I have no clue, what just those 3 modules have in common, that they can't be shown, when all the other modules work perfectly. Maybe you can help me.

**Comment by elorand** [comment]
Ah I see. Thank you for your quick help!

**Comment by eouia** [comment]
Seems answered.
