### ISSUE TITLE
Random Past Events showing up in the "future"

### ISSUE THREAD

**Issue by spudgy890** [MMRIZE/MMM-CalendarExt3#30]
Hello!

First I would like to say thank you for creating this wonderful module. 

The current issue I am facing is that past events are showing up in the future. For example I have an event on Aug 11 and 12 but it is showing up as September 11 and 12 which is wrong. I am currently using the secret .ical link provided by Google Calendar. Any guidance would be great! 

Here is the snippet:

```
{
                        module: "calendar",
                        header: "My Calendar",
                        //position: "top_left",
                        config: {
                                broadcastPastEvents: true, // <= IMPORTANT to see past events
				calendars:    [
                                                {
                                                symbol: "calendar-check",
                                                url: "hidden for privacy"
                                                }
                                      ]

                                }
                },
		{
  			module: "MMM-CalendarExt3",
  			position: "top_right",
  			config: {
    				mode: "week"
  				}
		},
```

**Comment by eouia** [comment]
Very weird.
Are those events are recurring events? I need more detailed information or
screenshots to guess what happens.

**Comment by spudgy890** [comment]
Also one more thing to add is that there's a "birthday" that is supposed to be November 5th but pops up as September 5th

**Comment by spudgy890** [comment]
So I did a little test and it seems like the calendar module is fine. I don't see any events that aren't supposed to be there. Unfortunately I can not share the .ical file as it is not my calendar but a significant other's calendar because it's a gift for them and they have some sensitive information on it

**Comment by eouia** [comment]
Without resources, I cannot guess anything.
At least show me the screenshots and your configuration.

To make things simpler, Leave all other modules out except `calendar` and `MMM-CalendarExt3` modules. Then let's see what happens. Then send me the config.js and screenshots.

**Comment by spudgy890** [comment]
Never mind I do see it in the OG calendar module. So I no longer think it is your module that is causing the problem. It's weird how the calendar is reading the ical link

**Comment by eouia** [comment]
Would you mind my closing this issue?
