### ISSUE TITLE
GLANCE notification issue

### ISSUE THREAD

**Issue by BlouZbee** [MMRIZE/MMM-CalendarExt3#32]
CX3_GLANCE_CALENDAR doesnt seem to respect the payload. All things being equal CX3_SET_DATE seems to change the view.

in Alexacontrol i have this:  notification: ["CX3_GLANCE_CALENDAR", "1"]

**Comment by eouia** [comment]
‘payload’ of this notification should be an object. So should be 

{ step: 1 }

**Comment by BlouZbee** [comment]
you are correct, thank you.
