### ISSUE TITLE
similar to google week view, time slots 

### ISSUE THREAD

**Issue by sdetweil** [MMRIZE/MMM-CalendarExt3#33]
have u considered something like this?   start/end time view 
working with my daughter/son in law, with busy schedules, trying to get common visualization,

![Screenshot at 2022-09-20 14-54-56](https://user-images.githubusercontent.com/1498142/191352212-fc36dc97-b1d7-4f1b-be41-c40068139a52.png)

**Comment by eouia** [comment]
I’m considering it already, but ‘timeline’(similar view for serial hour-based) would be introduced first.

**Comment by sdetweil** [comment]
so, timeline view is left/right
vs the other which up down

**Comment by eouia** [comment]
Right. Left to right for x hours. After introducing it then I’ll work your wish. (Almost done.)
