### ISSUE TITLE
MMM-GoogleCalendar Integration Shows All Day Event Times Incorrectly

### ISSUE THREAD

**Issue by nickloudermilk** [MMRIZE/MMM-CalendarExt3#36]
When all day events are pulled from MMM-GoogleCalendar broadcast, they appear to start the prior day at 7 PM (5 hours before their actual starting time of midnight). I am in a time zone that is exactly UTC-5. 

**MMM-GoogleCalendar Config:**
```
{
			module: 'MMM-GoogleCalendar',
			hiddenOnStartup: true,
			config: {
				broadcastPastEvents: true,
				broadcastEvents: true,
				calendars: [

```
**MMM-CalendarExt3 Config:**
```
{
			module: "MMM-CalendarExt3",
			position: "bottom_bar",
			config: {
				weeksInView: 3,
				weekIndex: 0,
				firstDayOfWeek: 0,
				locale: 'en-US',
				useSymbol: false,
				fontSize: "20px",
eventTransformer: (e) => {
  e.startDate = new Date(e.start?.date || e.start?.dateTime).valueOf()
  e.endDate = new Date(e.end?.date || e.end?.dateTime).valueOf()
  e.title = e.summary
  e.fulldayEvent = (e.start?.date) ? true : false
  return e
}
			}
		  }, 
```

![Screenshot](https://user-images.githubusercontent.com/6845213/196067914-377e63b3-a37d-4979-a247-b630126d9bb4.PNG)

**Comment by eouia** [comment]
How about it displayed on the original MMM-GoogleCalendar module? Frankly, this module doesn't parse the time of event. MMM-GoogleCalendar parses the event time, then this module use the parsed result. So, if the time is not parsed properly, maybe it might be the business of MMM-GoogleCalendar.

**Comment by technickl** [comment]
All day events appear correctly in the original MMM-GoogleCalendar module. Times for events that are not all day appear correctly. I.e. in the example above, "Matt out" does start at 8:00 AM local time on Tuesday.

**Comment by Bovive** [comment]
I have this same problem. Did you find a fix? Thanks!

**Comment by ccortellinijc** [comment]
The eventTransformer arrow function has a bug in it.  When you create a date without a time (e.g. new Date('01/01/2023')), then the time defaults to 00:00 UTC.  I corrected this as follows:

```
eventTransformer: (e) => {
  e.startDate = new Date(e.start?.date ? e.start.date + ' 00:00' : null || e.start?.dateTime).valueOf()
  e.endDate = new Date(e.end?.date ? e.end.date + ' 00:00' : null || e.end?.dateTime).valueOf()
  e.title = e.summary
  e.fulldayEvent = (e.start?.date) ? true : false
  return e
}
```

**Comment by eouia** [comment]
@ccortellinijc That is a great point! I never have realized `new Date('2023-01-01')` and `new Date('01/01/2023')` have different result!
Anyway I'm waiting `Temporal` API is introduced in real JS world. JS default `Date` object is not perfect to handle calendar things. After Temporal API, I'll rewrite the whole module with it. 

I'll change the tip with yours in README.md in the next update. Thanks.

**Comment by ruralguru** [comment]
used @ccortellinijc tip:

This fixed multi-day events.
Single day events now display as regular events starting at 12:00 AM.
@ccortellinijc  was that the effect you had as well or am I missing content?

**Comment by eouia** [comment]
@ruralguru
The root of this issue would be caused by this - `MMM-GoogleCalendar` doesn't respect the default `calendar` module's broadcasting event notification format.

The default calendar would emit the event with this format;
https://github.com/MMRIZE/MMM-CalendarExt3#handling-events

But that of `MMM-GoogleCalendar` is not compatible;
- `fullDayEvent` - missing.
- `start.date` and `end.date` is used instead of `start.dateTime` and `end.dateTime` on `fulldayevent`, but original `calendar` module doesn't have them, not compatible so we need some converting like this tip mentioned.


The easy and conventional way to solve this issue might be; Ask the developer of `MMM-GoogleCalendar` to edit that format to be compatible with de-facto default event format.

**Comment by ruralguru** [comment]
I was struggling to see the event structure. Thank you for noting the deviations.
I suspected the ? Was an inquiry, just couldn't find the start.date reference rather than startDate

**Comment by eouia** [comment]
Check #31
