### ISSUE TITLE
not showing up any calendar apointments

### ISSUE THREAD

**Issue by ele19735** [MMRIZE/MMM-CalendarExt3#41]
![image](https://user-images.githubusercontent.com/118017804/201415248-7aa2ebd8-1059-405b-84d5-33071e05b6c1.png)

Can anyone help me with not showing up any apointment ? honestly im pretty lame in this and mostly what ive done is based on manuals from github.

Thanks, Martin

**Comment by r4zi3lrrr** [comment]
Hi,

I've also got the same issue.

Here is my config:

	},
		{
  module: "MMM-CalendarExt3",
  position: "bottom_center",
  title: "",
  config: {
    mode: "month",
    instanceId: "basicCalendar",
    locale: 'en',
    maxEventLines: 5,
    firstDayOfWeek: 1,
    calendarSet: ['uk_holiday', 'abfall', 'mytest'],
    
  }

**Comment by eouia** [comment]
@r4zi3lrrr @ele19735 
First, you should confirm your default `calendar` module options.
`maximumEntries`, `maximumNumberOfDays`, `boradcastEvents` should be set properly. Usually, you didn't set these values or didn't assign enough value to get events of nowadays before quota consumed by old events.

**Comment by eouia** [comment]
And to get more details; I need your `calendar` module configuration also.

**Comment by eouia** [comment]
Ok, It's nice to hear that. I'll close this. @r4zi3lrrr if you have a still issue, write a new issue or discussion board.

**Comment by r4zi3lrrr** [comment]
Hi,

I've just rebuilt my Magic Mirror from scratch a few weeks ago, so not sure it'll be that.

I'll try a reinstall of this Calendar ext3 module and see if it makes any difference. Thanks for sharing how you fixed it.
