### ISSUE TITLE
Full day event issue eventTransformer: for MMM-GoogleCalendar

### ISSUE THREAD

**Issue by crazyboy75** [MMRIZE/MMM-CalendarExt3#49]
I was having an issue with full day events not being blocked out on both MMM-CalendarExt3 and MMM-CalendarExt3Agenda. I cross checked some of the code with the MMM-GoogleCalendar code and spotted a missed capital letter which has fixed this issue for me.

![image](https://user-images.githubusercontent.com/86164656/211168648-5799bea5-687f-41bd-93ea-918885caaedf.png)

Image from the readme highlighting the error. lowercase "d" instead of uppercase "D"

![image](https://user-images.githubusercontent.com/86164656/211168530-fc3995d8-4222-4e6a-a460-40994086b387.png)

Image from MMM-GoogleCalendar.js showing Full day format.

corrected code:

eventTransformer: (e) => {
  e.startDate = new Date(e.start?.date || e.start?.dateTime).valueOf()
  e.endDate = new Date(e.end?.date || e.end?.dateTime).valueOf()
  e.title = e.summary
  e.fullDayEvent = (e.start?.date) ? true : false
  return e
}

This fixed the issue for me so I wanted to share to help other out.

**Comment by eouia** [comment]
Check #31
