### ISSUE TITLE
Using Glance notification to pan the calendar by multiple steps causes multiple refreshes. 

### ISSUE THREAD

**Issue by Whitling2k** [MMRIZE/MMM-CalendarExt3#51]
It appears that each notification to 'glance' the calendar triggers a new glanceTime timer.

This causes problems when panning the calendar view with multiple steps (for example, looking more than one week/month ahead, one period at a time).

After the glanceTime has elapsed, the calendar jumps back to the (let's call it: ) Today view.  e.g. if I send a glance notification for +1 month, look at the calendar, then another & look, then another & look - the calendar will jump back to the Today view 3 times.  Sometimes when I'm still 'glancing' as the glanceTime elapsed from the first notification has passed. 

Best case scenario, this causes lots of flickers, worst case scenario the calendar jumps all over the place as users fight the multiple resets with more glance notifications.

Would it be possible for each subsequent glance notification to check if a timer is still active from a previous glance notification - and if so, reset to the glanceTime value again?

**As an additional point - is it possible to revert back to "today" with a notification to Ext3?**

**Comment by eouia** [comment]
I'll check. 
I'm not using glancing often, so I haven't known it.
