### ISSUE TITLE
firstDayOfWeek: 0 not working

### ISSUE THREAD

**Issue by ParaDescartar123** [MMRIZE/MMM-CalendarExt3#54]
Everything else seems to be working.
Here is my config.
Am I doing something wrong?

`{
                        module: "MMM-CalendarExt3",
                        position: "bottom_bar",
                        useWeather: true,
                        weatherLocationName: "LOCATION",
                        mode: "month",
                        firstDayOfWeek: 0,
                        useSymbol: true,
                        minimalDaysOfNewYear: 1,
                        maxEventLines: 10,
                        waitFetch: 120 * 1000,
                        displayLegend: true,

                },`

**Comment by eouia** [comment]
Leave me more details.
Each `displayLegend` and `firstDayOfWeek` is individually not working? or describing both on same time is the issue?
Can you show me the screen what happened?

**Comment by ParaDescartar123** [comment]
Thanks. I'll start with one issue at a time.

Here is a screen shot showing that the first day of week is Monday instead of Sunday which is NOT expected if property firstDayOfWeek: 0.

![image](https://user-images.githubusercontent.com/69368032/216083943-3f0fd882-7085-45ad-aa1f-4fcbe3ae897a.png)

**Comment by eouia** [comment]
I'm not sure your configuration is proper.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1720610/216085042-686b636d-4930-49dd-9cea-81f35cb628d5.png">

```js
useWeather: true,
weatherLocationName: "LOCATION",
mode: "month",
firstDayOfWeek: 0,
useSymbol: true,
minimalDaysOfNewYear: 1,
maxEventLines: 10,
waitFetch: 120 * 1000,
displayLegend: true,
```
should be placed inside of `config: { }` of module.

So this probably be the right syntax;
```js
{
  module: "MMM-CalendarExt3",
  position: "bottom_bar",
  config: {
    useWeather: true,
    weatherLocationName: "LOCATION",
    mode: "month",
    firstDayOfWeek: 0,
    useSymbol: true,
    minimalDaysOfNewYear: 1,
    maxEventLines: 10,
    waitFetch: 120 * 1000,
    displayLegend: true,
  }
}
```

**Comment by ParaDescartar123** [comment]
Yikes, thanks for the tip.

Of course it works now.  Thanks!

**Comment by eouia** [comment]
Sounds so good. I'll close this issue.
