### ISSUE TITLE
No calendar entries in my Calendar

### ISSUE THREAD

**Issue by r4zi3lrrr** [MMRIZE/MMM-CalendarExt3#55]
Hi,

I'm getting Calendar entries on the default calendar that comes with MagicMirror, but no entries for the one that relates to this module.

Can you please help?

Probably something I've done but unsure as to what needs changing - please see screenshot.

![Capture](https://user-images.githubusercontent.com/38400294/216781047-abab91fc-aa0d-49de-b8c0-b87b8aa256cf.PNG)

**Comment by eouia** [comment]
Show me your full configuration. (If you want, you can send it via mail. eouia0819@gmail.com)

**Comment by cucki48432** [comment]
After the latest update I have the same problem - no entries anymore. Maybe there's an idea here? :-)

**Comment by eouia** [comment]
Did you send me your config? Without details I cannot guess anything.

**Comment by cucki48432** [comment]
> Did you send me your config? Without details I cannot guess anything.

It's now working. So there's no support needed at the moment. Thanks for your help.

**Comment by r4zi3lrrr** [comment]
Hi,

Just a quick one please any idea as to how to make the text in the calendar module a bit bigger?

In terms of the entries from my calendar.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
