### ISSUE TITLE
Inheretied customEvents: color

### ISSUE THREAD

**Issue by mephitis2** [MMRIZE/MMM-CalendarExt3#56]
When the base calendar has customEvents set:
`customEvents: [{keyword: 'Date', symbol: 'heart fa-solid fa-heart', color: "pink"}]`
The ♥ icon is respected but the color is ignored when displayed in a Ext3 view.
It's a simple fix by adding transforms in the Ext3 config:
```
eventTransformer: (ev) => {
     if (ev.title.search('Date') > -1) ev.color = 'pink'
     return ev
}
```
But it would simplify configs if that redundancy wasn't needed.
Ideally transformers would be the 'final' override that can be done before rendering the display,

**Comment by eouia** [comment]
You are right. There is some priority issue on the `enventTransformer`. I already know that.
I'm refactoring my CX3 suites(CX3, CX3A, CX3T) to share one library, but not finished.
In my CX3T, I introduced `preProcessor` for raw data manipulate and moved `eventTransformer` to the final stage. I have a plan to implement that also into CX3 and CX3A, but not have enough time to do it yet. Anyway, I'll do it in a few weeks when I get a time.
Plz wait a while.

Ref. https://github.com/MMRIZE/MMM-CalendarExt3Timeline#110-2023-01-04

**Comment by eouia** [comment]
Check #31

**Comment by dakillian12** [comment]
I am seeing this issue again on the main branch. As described above, when customEvents are defined for the default calendar module, the customEvent symbol is being displayed in the Ext3 view, but not showing the custom color. I have applied the same workaround as mentioned for now.

I feel there must be something I am missing, but am not sure what it could be

**Comment by eouia** [comment]
Could you give me more details? What you did and what you expect and what you get.

**Comment by dakillian12** [comment]
Sure.
`{ url: "", name: "us_holidays", color: "#C2B280", symbol: "gift"}`

I have this calendar defined to display US Holidays. I didn't include the url, but it reads data fine.
I then defined some customEvents in the default calendar module as well. For example,
`{keyword: "Halloween", symbol: "ghost", color: "orange"}`

In this case, the Halloween event in the CalendarExt3 displays the correct symbol, but the color remains the one defined for the entire calendar. Hopefully this is detailed enough. If it would be helpful, I could give you the entire config file that I am using.

Thanks for your help!

**Comment by eouia** [comment]
Now I understand what happened.
The  default calendar module doesn't reflect `color` changed by `customEvents` (but symbol is reflexed). I don't know why. Maybe the developer forgot to implement that feature. Ask him.
Or you can manually assign custom color by `eventTransformer`, `preProcessor` or `eventPayload` of this module. (read README)
