### ISSUE TITLE
ics links not working

### ISSUE THREAD

**Issue by treypop** [MMRIZE/MMM-CalendarExt3#58]
I can't get the link to my calendars to work. 
![image](https://user-images.githubusercontent.com/24729682/222860846-826571f0-fda2-4330-863a-7f302ca8a327.png)

```
let config = {
  modules: [
	{
  module: "MMM-CalendarExt3",
  position: "bottom_center",
  config: {
	mode: "month",
    locale: 'us-US',
    maxEventLines: 5,
    firstDayOfWeek: 0,
	url: "https://calendar.google.com/calendar/ical/en.usa%23holiday%40group.v.calendar.google.com/public/basic.ics",
	name: "Holidays",
	color: "red",
    calendarSet: ['Holidays'],
  }
},
    {
    module: "clock",
    position: "top_center", // This can be any of the regions.
    config: {
		timezone:'America/New_York',
		timeFormat:'12',
		showPeriod:false,
		showDate:false,
      // The config property is optional.
      // See 'Configuration options' for more information.
    },
  },
]
};
```

**Comment by eouia** [comment]
This module doesn’t read the ics directly.
You need the default ‘calendar’ module or equivalent alternative that can emit events notifications.
This module subscribes that notifications then draw them pretty.

**Comment by treypop** [comment]
> This module doesn’t read the ics directly. You need the default ‘calendar’ module or equivalent alternative that can emit events notifications. This module subscribes that notifications then draw them pretty.

Alright will add that and see if it works

**Comment by treypop** [comment]
That fixed my problem
