### ISSUE TITLE
Weather units do not match locale

### ISSUE THREAD

**Issue by BigJoe1979** [MMRIZE/MMM-CalendarExt3#63]
I'm in the US, where we stubbornly use different units than the rest of the civilized world.

I have my MM config set for locale: "en-US", and the weather module displays temps in F whereas CalendarExt3 displays them in C.  Is there a setting I can change this?

**Comment by eouia** [comment]
What your weather module said?

**Comment by eouia** [comment]
I'll try to guess what happen.

**Comment by eouia** [comment]
Just only unit is false? Or the value itself is calculated as Celsius than Fahrenheit?

**Comment by eouia** [comment]
Hmmm, weird. Nothing seems wrong in my module. Because, My module handle any `unit` from weather information, even `C` or `F`, anything.
Could you show me your `weather` module configuration? (only except API Key) Are you using `openweathermap` API or other else?

**Comment by eouia** [comment]
I found out what was wrong. The broadcasting messages of the default weather module don't respect the `units` of the configuration of weather. module Internally, it gets metric units from API by default and then coverts them into `imperial` unit to show in MagicMirror when it is configured as `imperial`, but broadcasts the unconverted original `metric` values. 
So this is not the fault of my module. Ask MichMich or someone to fix the default weather module.
