### ISSUE TITLE
[v2] Calendar Icon Colors Missing

### ISSUE THREAD

**Issue by zanix** [MMRIZE/MMM-CalendarExt3#68]
Calendar icon colors are missing from events. All-day events still have the correct background color.

**Comment by Gruenergecko** [comment]
I have the same Problem

**Comment by eouia** [comment]
The original default `calendar` module delivers only one `color` property. So there is no `bgColor` information or specific conditions (`coloredSymbol` or something)

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1720610/235889075-a6c152c1-b3e4-4b90-86b2-93a70ed43e87.png">

so, my module assumes, 
- Fullday event : Set that `color` as background,
- normal timed event : Set that `color` as dot or icon.

With my test, it seems to be working as intended. 
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/1720610/235891828-74c76833-b8d9-4e96-a739-59cb096fe177.png">


I need help to understand what you guys mentioned. Could you show me the screenshot and config to know `AS-IS` and `TO-BE`?

**Comment by Gruenergecko** [comment]
![Cal1](https://user-images.githubusercontent.com/132435574/235896692-fea56fce-a3b3-4859-a92c-c77fc33e65c6.jpg)
![cal2](https://user-images.githubusercontent.com/132435574/235896720-e8a82fec-223d-4a6d-a802-6edd0f9177ff.jpg)
![20230503_125104](https://user-images.githubusercontent.com/132435574/235897104-cfa65c1a-2341-481e-8e95-bc31ac0305d5.jpg)

**Comment by Gruenergecko** [comment]
the symbols of "Arbeit Kathi" were until recently red as they are configured

**Comment by eouia** [comment]
Ah, I was confused with CX3A. You are right. I'll check. thanks.

**Comment by eouia** [comment]
Updated. plz check it.

**Comment by Gruenergecko** [comment]
It works again.  Perfect

**Comment by zanix** [comment]
Works for me as well, thanks!
