### ISSUE TITLE
Unable to show ics files.

### ISSUE THREAD

**Issue by rcarnathan** [MMRIZE/MMM-CalendarExt3#7]
I am unable to get any content to show for ICS files from Google. I am using a private ICS file link which works with the native MM calendar module without error.

**Comment by eouia** [comment]
show me your config. This module is not working with standalone. The event data is derived from original MM calendar module.

**Comment by rcarnathan** [comment]
modules: [
		//{
		//	module: "clock",
		//	position: "top_right"
		//},
		{
			module: "MMM-CalendarExt3",
			position: "center",
			title: "Family Calendar",
			config: {
					broadcastPastEvents: true, // <= IMPORTANT to see past events
					mode: "week",
					weeksInView: "4",
					weekIndex: "0",
					instanceId: "Main",
					maxEventLines: 5,
					firstDayOfWeek: 1,
					calendarSet: [],
					
				calendars: [
					{
						url: "https://calendar.google.com/calendar/ical/tcarnathan77%40gmail.com/private-c8xxxx/basic.ics",
						name: "Tiffany", // <= RECOMMENDED to assign name
						color: "Red" // <= RECOMMENDED to assign color
					},
					{
						url: "https://calendar.google.com/calendar/ical/980bhdk8qnqqpjbnb0rn7smpag%40group.calendar.google.com/private-c0axxxxxx/basic.ics",
						name: "Alyson", // <= RECOMMENDED to assign name
						color: "Pink" // <= RECOMMENDED to assign color
					},
					{
						url: "https://calendar.google.com/calendar/ical/tsmnshq381mi7elni0oqganfh0%40group.calendar.google.com/private-ba9xxxxx/basic.ics",
						name: "Ethan", // <= RECOMMENDED to assign name
						color: "Blue" // <= RECOMMENDED to assign color
					},
				]
			}
		},
	]

**Comment by eouia** [comment]
“calendars” don’t belong to this module. Use MM’s original “calendar” module together.

**Comment by rcarnathan** [comment]
What is the format requirements?

**Comment by rcarnathan** [comment]
Figured it out. Cheers.
