### ISSUE TITLE
Is there a way to hide the calendar module?

### ISSUE THREAD

**Issue by xaglen** [MMRIZE/MMM-CalendarExt3#83]
CalendarExt3 needs the default calendar module to be active, but that means that events are displayed twice.

Is there a way to hide the calendar module it so that only CalendarExt3 displays? In other words, can the calendar module do all the things it needs to do for CalendarExt3 to run without actually rendering anything to the MagicMirror?

**Comment by eouia** [comment]
Just remove ‘position’ properly from the default calendar module. Or hide it with CSS.

**Comment by xaglen** [comment]
Thanks! I didn't realize position could be blank. That's super-easy!
