### ISSUE TITLE
Unable to update from 1.3.1 to 1.4.0

### ISSUE THREAD

**Issue by Stoked18** [MMRIZE/MMM-CalendarExt3#84]
All updates up until 1.3.1 were successful without any problems. Now I am not able to update to 1.4.0.
See below:

![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/131020171/aaf18c13-3938-4d54-8919-134fdde3f762)

Thanks in advance for any help :)

**Comment by eouia** [comment]
You might have modified source code by yourself. It prevents git pull. Anyway the easiest way is just remove directory then reinstall again. Not so difficult or pain.
