### ISSUE TITLE
Does not appear, console says missing CX3_shared.mjs

### ISSUE THREAD

**Issue by markcharlesobrien** [MMRIZE/MMM-CalendarExt3#86]
I am trying to use MMM-CalendarExt3 on the MagicMirror Docker container linked in the docs.

Per the instructions here, I cloned MMM-CalendarExt3 in the modules directory and ran npm install. I put the minimal config from your readme into my config.js. When I refresh the calendar, the module does not appear. In the Javascript Console, I get the error `Failed to load resource :8080/modules/MMM-CalendarExt3/CX3_shared.mjs:1: the server responded with a status of 404 (Not Found)` and `TypeError: Failed to fetch MMM-CalendarExt3.js:109 dynamically imported module: http://[my IP]:8080/modules/MMM-CalendarExt3/CX3_Shared/CX3_shared.mjs`

If I go into the container, the directory modules/MMM-CalendarExt3/CX3_Shared is empty.

What am I doing wrong?

**Comment by eouia** [comment]
![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/1720610/dcd85bf2-d349-43ca-a7d0-a33f0acdbd7c)

**Comment by markcharlesobrien** [comment]
Guess I missed that. Thanks
