### ISSUE TITLE
Module not showing up

### ISSUE THREAD

**Issue by manshurtigh** [MMRIZE/MMM-CalendarExt3#87]
Hi! 

After installing the module and adding the configuration into config.js the calendar doesn't show up. I've tried remove every option, but nothing seems to work.

I can see that the module shows up in the HTML, but it just says "undefined" and the calendar is not showing up on the mirror.

Anyone else had this or similar problem?

**Comment by eouia** [comment]
Show me the configuration of modules. (If possible, whole config.js)
(eouia0819@gmail.com)

**Comment by manshurtigh** [comment]
Thanks for the prompt response.

I added the below into the config.js and this module immediately started working. I overlooked that I had to load the standard calendar into the config.js even though it correctly says so in the ReadMe.

```
{
module: "calendar",
},
```
