### ISSUE TITLE
Error start date for past full day event

### ISSUE THREAD

**Issue by markmingjie** [MMRIZE/MMM-CalendarExt3#94]

**Comment by eouia** [comment]
It might be a bug in the default calendar module.
![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/1720610/268ce94a-287d-4b82-b162-61a4ecd981dd)

**Comment by markmingjie** [comment]
> It might be a bug in the default calendar module. ![image](https://user-images.githubusercontent.com/1720610/271192050-268ce94a-287d-4b82-b162-61a4ecd981dd.png)

Thank you so much! I have been trying to describe what just happened, then you just give me the right answer.
