### ISSUE TITLE
Week number showing on all days of a given week

### ISSUE THREAD

**Issue by dewwy1** [MMRIZE/MMM-CalendarExt3#99]
hey, I updated to the latest version prior to this release (1.6 I believe) and noticed this issue. From memory this was not default behavior previously.

I updated the MMM-CalendarExt3.js file to comment out lines 379 to 383 which did the trick.

I also tried chanign line 60 "displayCW" to false, no luck.

![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/95069643/d336e6ed-74bc-4581-8f79-2fa6dfdb71a5)

Any chance this can become an option/config in future releases? Or have it just show on the first of the week?

**Comment by eouia** [comment]
I think you might have broken this CSS rule. (overriding in custom.css or somewhere, or corruption in MMM-CalendarExt3.css)
```css
/* MMM-CalendarExt3.css: 122 */
.CX3 .cw:not(.cwFirst) {
  display: none;
}
```
You can check what causes these breaks by <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> on MM. It will open the dev console. You can inspect applied CSS rules on specific elements. It will something like this;

![image](https://github.com/MMRIZE/MMM-CalendarExt3/assets/1720610/a839082f-3122-4674-aa03-c68845ec62e8)

**Comment by eouia** [comment]
There is no reply. I'll close.

**Comment by dewwy1** [comment]
Thanks eouia, had a look and tried the default CSS and worked fine. not sure what caused it in the end.
